name: build, and test
on:
  workflow_dispatch:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java  JDK
        uses: actions/setup-java@v1.4.4
        with:
         java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
      - name: build
        run: |
          ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: jarka
          path: ./build/libs/flashcards-0.0.1-SNAPSHOT-all.jar
