name: build, and test
on:
  workflow_dispatch:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java DK
        uses: actions/setup-java@v3
        with:
         java-version: 17
         distribution: temurin
      - name: build
        run: ./gradlew build
      - name: craft artifact 
        run: ./gradlew bootjar
      - name: upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: jarka
          path: ./build/libs/flashcards_bootjar.jar