name: build, and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java  JDK
        uses: actions/setup-java@v1.4.4
        with:
         java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: test
        run: ./gradlew test
