name: build, and test
on:
  workflow_dispatch:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java DK
        uses: actions/setup-java@v1.4.4
        with:
         java-version: 17
      - name: build
        run: |
          ./gradlew build
          ./gradlew bootjar
      - name: upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: jarka
          path: ./build/libs/flashchards_bootjar.jar
