name: build artifact
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java  JDK
        uses: actions/setup-java@v1.4.4
        with:
         java-version: 17
      - name: test
        run: ./gradlew test
